// <auto-generated>
// This file was generated by MauiStyleGenerator from RapidXaml.CodeGen.Maui
// learn more at https://github.com/mrlacey/XamlStyleTypes
// </auto-generated>


namespace MonkeyFinder
{
    public static partial class AppColors
    { 
        public const string Primary = "Primary";
        public const string PrimaryDark = "PrimaryDark";
        public const string Accent = "Accent";
        public const string LightBackground = "LightBackground";
        public const string DarkBackground = "DarkBackground";
        public const string CardBackground = "CardBackground";
        public const string CardBackgroundDark = "CardBackgroundDark";
        public const string LabelText = "LabelText";
        public const string LabelTextDark = "LabelTextDark";
    }

}

