// <auto-generated>
// This file was generated by MauiStyleGenerator from RapidXaml.CodeGen.Maui
// learn more at https://github.com/mrlacey/XamlStyleTypes
// </auto-generated>


namespace MonkeyFinder
{

    public class BaseLabel : Label
    {
        public BaseLabel()
        {
            if (App.Current.Resources.TryGetValue("BaseLabel", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class MicroLabel : Label
    {
        public MicroLabel()
        {
            if (App.Current.Resources.TryGetValue("MicroLabel", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class SmallLabel : Label
    {
        public SmallLabel()
        {
            if (App.Current.Resources.TryGetValue("SmallLabel", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class MediumLabel : Label
    {
        public MediumLabel()
        {
            if (App.Current.Resources.TryGetValue("MediumLabel", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class LargeLabel : Label
    {
        public LargeLabel()
        {
            if (App.Current.Resources.TryGetValue("LargeLabel", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class ButtonOutline : Button
    {
        public ButtonOutline()
        {
            if (App.Current.Resources.TryGetValue("ButtonOutline", out object result))
            {
                this.Style = result as Style;
            }
        }
    }

    public class CardView : Border
    {
        public CardView()
        {
            if (App.Current.Resources.TryGetValue("CardView", out object result))
            {
                this.Style = result as Style;
            }
        }
    }
}

